### ISSUE TITLE
Rspec failure in existing v0.5.1

### ISSUE THREAD

**Issue by rnelson0** [thias/puppet-bind#44]
When looking at #43, I found that there was an existing failing unit test. I did not correct it to keep commits contained to the related problem. I would suggest either setting the unit test to look for 'service named reload', or removing it entirely since I do not see where the class sets this information anyway.

Failures:

  1) bind::server
     Failure/Error: })}
       expected that the catalogue would contain Service[named] with restart set to `"/sbin/service named reload"` but it is set to `"service named reload"` in the catalogue
     # ./spec/classes/bind_server_spec.rb:14:in `block (2 levels) in <top (required)>'

**Comment by thias** [comment]
Closing, but keeping #64 open, as that's where the relevant changes are.
